# Befor running HorizontalPodAutoscaler make sure metric server is installed in the EKS.
# Metric server is responsible for measuring the memory consumption of the pods in kubernetes.
# to install metric server run this command:
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
# 1.Install Metric Server
# $ kubectl top pod
# 2.resource definition inside pod
# #.HPA should be attached to the deployment
#Horizontal Pod Autoscaling is used to create new nodes based on the cpu utilization of each node
#Horizontal Pod Autoscaler should be attached to the deployment 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment #your frontend type
    name: frontend #your deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization #if averageUtilization of server shoud less than 50 or else it will create new pod
        averageUtilization: 50

# $ kubectl get hpa